# Generated by Django 5.0.2 on 2024-03-13 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('message', models.TextField(blank=True, null=True)),
                ('doctor', models.ForeignKey(choices=[('Dr. Smith', 'Dr. Smith - Cardiology'), ('Dr. Johnson', 'Dr. Johnson - Neurology'), ('Dr. Lee', 'Dr. Lee - Pediatrics'), ('Dr .Leo', 'Dr. Leo - X-Ray')], on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
