# Generated by Django 5.0.2 on 2024-03-11 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_alter_appointment_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.CharField(choices=[('Dr. Smith', 'Dr. Smith - Cardiology'), ('Dr. Johnson', 'Dr. Johnson - Neurology'), ('Dr. Lee', 'Dr. Lee - Pediatrics'), ('Dr .Leo', 'Dr. Leo - X-Ray')], max_length=100),
        ),
    ]
