# Generated by Django 5.0.2 on 2024-02-14 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
