# Generated by Django 5.0.2 on 2024-02-16 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_alter_registration_phone_number'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='registration',
            table='registration_registration',
        ),
    ]
